CREATE DATABASE QLTV
USE QLTV

CREATE TABLE SACH
(
 MASACH CHAR(20) not null,
 TENSACH NVARCHAR(50),
 SOLUONG INT,
 NHAXB NVARCHAR(50),
 THELOAI NVARCHAR(50),
 TACGIA NVARCHAR(50),
 CONSTRAINT PK_MS PRIMARY KEY (MASACH),
)
CREATE TABLE MUONTRA
(
 MASV CHAR(20) NOT NULL, 
 MASACH CHAR(20) NOT NULL,
 NGAYMUON CHAR(10),
 NGAYTRA CHAR(10),
 SOLUONG INT,
 QLTHUVIEN NVARCHAR(50),
 CONSTRAINT PK_msv PRIMARY KEY (MASV, MASACH),
 CONSTRAINT FK_MS FOREIGN KEY (MASACH) REFERENCES SACH (MASACH)
)





